name: shop_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  badges: ^2.0.3
  bloc: ^8.1.0
  build_runner: ^2.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.17.0
  json_serializable: ^6.3.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/No_Product_Found.png
    - assets/images/order.png
    - assets/images/order_image.png

